name: Stress Test
on: push
jobs:
  stress_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install k6
        run: sudo apt install k6
      - name: Run k6 Load Test
        run: k6 run stress-test.js
      - name: Run Cypress Tests
        run: npx cypress run --headless
